openapi: 3.0.3
info:
  title: Google Drive API
  description: An API to interact with Google Drive, allowing users to manage files, folders, and presentations.
  version: 1.1.0
servers:
  - url: http://localhost:8000
    description: Local development server
paths:
  /drive/list/{path}:
    get:
      summary: List Files in a Folder
      description: Retrieves the contents of a specific folder in Google Drive by its full path.
      operationId: list_drive_path_drive_list__path__get
      parameters:
        - name: path
          in: path
          required: true
          description: The full path of the folder to list the contents of.
          schema:
            type: string
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  files:
                    type: array
                    items:
                      $ref: '#/components/schemas/FileItem'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /drive/search:
    get:
      summary: Search Files and Folders
      description: Searches for files and folders by name in Google Drive.
      operationId: search_drive_drive_search_get
      parameters:
        - name: name
          in: query
          required: false
          description: The name of the file or folder to search for.
          schema:
            type: string
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/SearchResultItem'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /drive/document/{file_id}:
    get:
      summary: Get Google Document
      description: Retrieves a Google Document by its file ID.
      operationId: get_google_document_drive_document__file_id__get
      parameters:
        - name: file_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoogleDocument'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '404':
          $ref: '#/components/responses/NotFoundError'
  /drive/spreadsheet/{file_id}:
    get:
      summary: Get Google Spreadsheet
      description: Retrieves a Google Spreadsheet by its file ID.
      operationId: get_google_spreadsheet_drive_spreadsheet__file_id__get
      parameters:
        - name: file_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoogleSpreadsheet'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '404':
          $ref: '#/components/responses/NotFoundError'
  /drive/presentations:
    post:
      summary: Create Google Presentation
      description: Creates a new, empty Google Slides presentation.
      operationId: create_google_presentation_drive_presentations_post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PresentationCreate'
      responses:
        '201':
          description: Presentation Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PresentationInfo'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /drive/presentations/{presentation_id}:
    get:
      summary: Get Google Presentation
      description: Retrieves a Google Slides presentation by its ID.
      operationId: get_google_presentation_drive_presentations__presentation_id__get
      parameters:
        - name: presentation_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoogleSlides'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '404':
          $ref: '#/components/responses/NotFoundError'
  /drive/presentations/{presentation_id}/slides:
    post:
      summary: Add Slide to Presentation
      description: Adds a new slide with a specified layout and content to an existing presentation.
      operationId: add_slide_to_presentation_drive_presentations__presentation_id__slides_post
      parameters:
        - name: presentation_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SlideContent'
      responses:
        '201':
          description: Slide Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SlideCreationResponse'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    FileItem:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        mimeType:
          type: string
    SearchResultItem:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        mimeType:
          type: string
        path:
          type: string
    Error:
      type: object
      properties:
        detail:
          type: string
    GoogleDocument:
      type: object
      description: The JSON representation of a Google Document.
    GoogleSpreadsheet:
      type: object
      description: The JSON representation of a Google Spreadsheet.
    GoogleSlides:
      type: object
      description: The JSON representation of a Google Slides presentation.
    Presentation:
      type: object
      properties:
        presentation_id:
          type: string
        title:
          type: string
        slides:
          type: array
          items:
            $ref: '#/components/schemas/Slide'
    Slide:
      type: object
      properties:
        slide_id:
          type: string
        layout:
          type: string
        title:
          type: string
          nullable: true
        subtitle:
          type: string
          nullable: true
        body:
          type: string
          nullable: true
    PresentationCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          description: The title for the new presentation.
          example: "My New Presentation"
    PresentationInfo:
      type: object
      properties:
        id:
          type: string
          description: The ID of the newly created presentation.
        name:
          type: string
          description: The name of the newly created presentation.
    SlidePayload:
      type: object
      required:
        - layout
      properties:
        layout:
          type: string
          description: The layout for the new slide.
          example: "TITLE_AND_BODY"
        title:
          type: string
          description: The title text for the slide.
        subtitle:
          type: string
          description: The subtitle text for the slide.
        body:
          type: string
          description: The body text for the slide.
    SlideCreationResponse:
      type: object
      properties:
        slideId:
          type: string
          description: The ID of the newly created slide.
  responses:
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
